# Generated by Django 5.2.17 on 2026-09-02 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('sham_cash', 'شام كاش')], max_length=20)),
                ('provider_reference_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('succeeded', 'ناجح'), ('failed', 'فاشل')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raw_webhook_payload', models.JSONField(blank=True, help_text='للتدقيق فقط — لا يُستخدم بمنطق العمل', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order'], name='payments_pa_order_i_1d1c93_idx'), models.Index(fields=['provider_reference_id'], name='payments_pa_provide_5d775b_idx')],
            },
        ),
    ]
